# Generated by Django 5.2.6 on 2025-09-21 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this alert. Null for system-generated alerts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_official',
            field=models.BooleanField(default=False, help_text='True for alerts created by admins or official sources'),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active')], default='ACTIVE', help_text='Current verification status of the alert', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='verification_score',
            field=models.IntegerField(default=0, help_text='Calculated score based on user votes (upvotes - downvotes)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='hazard_type',
            field=models.CharField(choices=[('AIR_RAID', 'Air Raid'), ('DRONE', 'Drone'), ('MISSILE', 'Missile'), ('FLOOD', 'Flood'), ('FIRE', 'Fire'), ('INDUSTRIAL', 'Industrial Accident'), ('SHOOTING', 'Shooting'), ('STORM', 'Storm'), ('TSUNAMI', 'Tsunami'), ('CHEMICAL WEAPON', 'Chemical Weapon'), ('BIOHAZARD', 'Biohazard'), ('NUCLEAR', 'Nuclear'), ('UNMARKED SOLDIERS', 'Unmarked Soldiers'), ('PANDEMIC', 'Pandemic'), ('TERRORIST ATTACK', 'Terrorist Attack'), ('MASS POISONING', 'Mass Poisoning'), ('CYBER ATTACK', 'Cyber Attack'), ('EARTHQUAKE', 'Earthquake')], max_length=20),
        ),
        migrations.CreateModel(
            name='AlertVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
