# Generated by Django 5.2.6 on 2025-09-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_created_by_alert_is_official_alert_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the alert', null=True),
        ),
    ]
