# Generated by Django 5.2.6 on 2025-09-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['lat'], name='shelters_sh_lat_590fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['lon'], name='shelters_sh_lon_f4ef8f_idx'),
        ),
    ]
